apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-statistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.nais.adeo.no/statistikk
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isReady
`