apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-statistikk
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.nais.adeo.no/microfrontend-ressurser/statistikk
    liveness:
        initialDelay: 5
        path: /microfrontend-ressurser/statistikk/internal/isAlive
    readiness:
        initialDelay: 5
        path: /microfrontend-ressurser/statistikk/internal/isReady
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: STATISTIKK_API_URL
          value: https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-statistikk-api
