apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-statistikk
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.intern.nav.no/rekrutteringsbistand-statistikk
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isReady
