apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-statistikk
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.dev.intern.nav.no/rekrutteringsbistand-statistikk
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-statistikk/internal/isReady
    azure:
      application:
        enabled: true
        claims:
          extra:
            - NAVident
      sidecar:
        enabled: true
    accessPolicy:
      outbound:
        external:
          - host: rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: STATISTIKK_API_URL
          value: https://rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io/rekrutteringsbistand-statistikk-api
