apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-statistikk
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://rekrutteringsbistand.nais.preprod.local/statistikk
    liveness:
        initialDelay: 5
        path: /statistikk/internal/isAlive
    readiness:
        initialDelay: 5
        path: /statistikk/internal/isReady
